spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/exam?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  access-token:
    secret-key: accesssecretkeyaccesssecretkeyaccesssecretkeyaccesssecretkeyaccesssecretkeyaccesssecretkey
    expiration-minutes: 60
  refresh-token:
    secret-key: refreshsecretkeyrefreshsecretkeyrefreshsecretkeyrefreshsecretkeyrefreshsecretkeyrefreshsecretkey
    expiration-minutes: 600

